version: '3.8'

services:
  # Backend Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production
    container_name: todo-server-prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb+srv://rexxy:962239@playground1.oocy9.mongodb.net/todo-test
    ports:
      - "5000:5000"
    networks:
      - todo-network

  # Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
    container_name: todo-client-prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge 